<?php include_once __DIR__ . '/../header.html'; ?>
    <div class="container">
         <div class="row">
             <a href="/categories/create">Nova Categoria</a>
             <h3>Listagem de Categorias</h3>
             <table class="table">
                 <thead>
                    <tr>
                        <th>Id</th>
                        <th>Nome</th>
                        <th>Ações</th>
                    </tr>
                 </thead>
                 <tbody>
                    <?php foreach ($categories as $category): ?>
                    <tr>
                        <td><?php echo $category->getId(); ?></td>
                        <td><?php echo $category->getName(); ?></td>
                        <td><?php echo "<a href='/categories/{$category->getId()}/edit'>Editar</a>";?> |
                        <?php echo "<a href='/categories/{$category->getId()}/remove'>Excluir</a>";?></td>
                    </tr>
                    <?php endforeach; ?>
                 </tbody>
             </table>
         </div>
    </div>
<?php include_once __DIR__ . '/../footer.html'; ?>